config: config.yml
debug: false
log-to-file: false
log-to-file-compress: false
log-to-file-max-age: 28
log-to-file-max-backups: 3
log-to-file-max-size: 500
log-to-file-path: /tmp/socketcli.log
log-to-stdout: true
stop-after: false
stop-after-time: 1m0s
time-format: 2006/01/02 - 15:04:05
websocket-address: wss://chaotic-stream.herokuapp.com
